spring:
  datasource:    url: jdbc:mysql://localhost/gc?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: abc123!!
    driver-class-name: com.mysql.jdbc.Driver
  cache: 
    ehcache: 
      config: classpath:ehcache.xml  jpa:    show-sql: true