ALTER TABLE `t_gc_db_category`
ADD COLUMN `EXPLAIN`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分类解释' AFTER `CATEGORY_TYPE`,
ADD COLUMN `CONTAIN`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分类包含' AFTER `EXPLAIN`,
ADD COLUMN `TIP`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '小贴士' AFTER `CONTAIN`;

