CREATE TABLE `t_gc_db_lookup_value` (
`LKV_ID`  int NOT NULL AUTO_INCREMENT COMMENT '值列ID' ,
`LOOKUP_TYPE_CODE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '类型编码' ,
`LOOKUP_TYPE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '类型' ,
`LOOKUP_KEY`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '类型包含键值' ,
`LOOKUP_VALUE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '类型包含映射值' ,
`VALUE_DESC`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '值描述' ,
`ORDER_NO`  int NULL DEFAULT NULL COMMENT '顺序' ,
`CREATED_TIME`  datetime NOT NULL DEFAULT now() COMMENT '创建时间' ,
`IS_ENABLE`  tinyint NOT NULL DEFAULT 1 COMMENT '是否可用：1，可用 0，不可用' ,
PRIMARY KEY (`LKV_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;

INSERT INTO t_gc_db_lookup_value(LOOKUP_TYPE_CODE,LOOKUP_TYPE,LOOKUP_KEY,LOOKUP_VALUE,VALUE_DESC,ORDER_NO) VALUES ('GC001','垃圾分类接口映射','可回收','1','choviwu接口的可回收映射我们的CATEGORY_ID=1',0);
INSERT INTO t_gc_db_lookup_value(LOOKUP_TYPE_CODE,LOOKUP_TYPE,LOOKUP_KEY,LOOKUP_VALUE,VALUE_DESC,ORDER_NO) VALUES ('GC001','垃圾分类接口映射','有害垃圾','2','choviwu接口的有害垃圾映射我们的CATEGORY_ID=2',1);
INSERT INTO t_gc_db_lookup_value(LOOKUP_TYPE_CODE,LOOKUP_TYPE,LOOKUP_KEY,LOOKUP_VALUE,VALUE_DESC,ORDER_NO) VALUES ('GC001','垃圾分类接口映射','湿垃圾','3','choviwu接口的湿垃圾映射我们的CATEGORY_ID=3',2);
INSERT INTO t_gc_db_lookup_value(LOOKUP_TYPE_CODE,LOOKUP_TYPE,LOOKUP_KEY,LOOKUP_VALUE,VALUE_DESC,ORDER_NO) VALUES ('GC001','垃圾分类接口映射','干垃圾','4','choviwu接口的干垃圾映射我们的CATEGORY_ID=4',3);
