CREATE TABLE `T_GC_DB_GARBAGE_INFO` (
`GARBAGE_ID`  int NOT NULL AUTO_INCREMENT COMMENT '垃圾ID' ,
`GARBAGE_NAME`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '垃圾名称' ,
`DESC`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '垃圾描述' ,
`ORIGIN`  tinyint NULL DEFAULT 1 COMMENT '数据来源：1,自己 2，外部接口 3，其他' ,
`ORIGIN_ADR`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据来源位置' ,
`CREATED_TIME`  datetime NOT NULL DEFAULT now() COMMENT '创建时间' ,
`IS_ENABLE`  tinyint NOT NULL DEFAULT 1 COMMENT '是否可用：1，可用 0，不可用' ,
PRIMARY KEY (`GARBAGE_ID`)
);

CREATE TABLE `T_GC_DB_CATEGORY` (
`CATEGORY_ID`  int NOT NULL AUTO_INCREMENT COMMENT '分类ID' ,
`CATEGORY_TYPE`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分类类型' ,
`ORIGIN`  tinyint NULL DEFAULT 1 COMMENT '数据来源：1,自己 2，外部接口 3，其他' ,
`ORIGIN_ADR`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据来源位置' ,
`CREATED_TIME`  datetime NOT NULL DEFAULT now() COMMENT '创建时间' ,
`IS_ENABLE`  tinyint NOT NULL DEFAULT 1 COMMENT '是否可用：1，可用 0，不可用' ,
PRIMARY KEY (`CATEGORY_ID`)
);

CREATE TABLE `T_GC_BU_GARBAGE_CLASSIFICATION` (
`GC_ID`  int NOT NULL AUTO_INCREMENT COMMENT '垃圾分类ID' ,
`GARBAGE_ID`  int NULL DEFAULT NULL COMMENT '垃圾ID' ,
`CATEGORY_ID`  int NULL DEFAULT NULL COMMENT '分类ID' ,
`ORIGIN`  tinyint NULL DEFAULT 1 COMMENT '数据来源：1,自己 2，外部接口 3，其他' ,
`ORIGIN_ADR`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据来源位置' ,
`CREATED_TIME`  datetime NOT NULL DEFAULT now() COMMENT '创建时间' ,
`IS_ENABLE`  tinyint NOT NULL DEFAULT 1 COMMENT '是否可用：1，可用 0，不可用' ,
PRIMARY KEY (`GC_ID`)
);
